### ISSUE TITLE
Option for `--comma-break`

### ISSUE THREAD

**Issue by karlhorky** [gajus/pg-formatter#8]
Hi @gajus,

Would it be possible to add an option for [the `--comma-break` option](https://github.com/darold/pgFormatter/blob/d5ffbbc/README?rgh-link-date=2020-11-28T15%3A33%3A55Z#L32)?

### With `--comma-break`

![Screen Shot 2020-11-28 at 16 34 18](https://user-images.githubusercontent.com/1935696/100521137-19aa8280-31a2-11eb-84ca-920af3a39a6a.png)

### Without `--comma-break`

![Screen Shot 2020-11-28 at 16 32 09 16 34 47](https://user-images.githubusercontent.com/1935696/100521147-31820680-31a2-11eb-978e-c24d17ad470e.png)

**Comment by gajus** [comment]
PR is welcome.

**Comment by richeyryan-geowox** [comment]
Hey @gajus,

So since my PR was merged, would it be possible to get a release for NPM?

Also could the version in eslint-plugin-sql be updated? I'm happy to make the PR once the new version of pg-formatter is pushed to NPM

**Comment by gajus** [comment]
Releases are automated. It looks like not all tests are passing:

https://travis-ci.com/github/gajus/pg-formatter/jobs/513308340

**Comment by richeyryan-geowox** [comment]
I noticed that alright when I forked the repo. Some test unrelated to what I added was failing. I can take a look at it to unblock the release.

**Comment by richeyryan-geowox** [comment]
I tried figuring out that failing test but I honestly couldn't figure out what the `anonymize` option is meant to do. I ran a few examples through the pgFormatter website and I couldn't pin down what effect `anonymize` was having. If you could clarify for me I'd be happy to take another look.

**Comment by nponiros** [comment]
I had a look at the failing test. The problem seems to be the pg-formatter version used (looks like anonymize is broken in v5.x). Using the latest version the test fails. Using v4.4 the test doesn't fail. V4.4 was the latest version the last time this package was release from what I can tell. @gajus it is probably a good idea to specify the version in the `build-pg-formatter` command. I can open a PR to force v4.4 and maybe as a second step you could release a new version of this package with v5.1 which fixes a bunch of bugs from what I can tell.

I opened an issue https://github.com/darold/pgFormatter/issues/265

**Comment by gajus** [comment]
Could you please update your PR to lock v4.4 version?

**Comment by nponiros** [comment]
Done
